#!/usr/bin/env python3
"""Generate agencies/_index.md — the human-readable agency overview: governance
class, where each agency publishes policies, what this repo holds for it, and
freshness. GENERATED (same pattern as llms.txt / REVIEW.md): counts derive from the
corpus via src/agency_profile.py; the curated columns come from
_meta/agency-profiles.yml. Never edit agencies/_index.md by hand.

  python3 src/build_agency_index.py           # regenerate
  python3 src/build_agency_index.py --check   # CI freshness check"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from agency_profile import overview
from repo_lib import REPO_ROOT

OUT = REPO_ROOT / "agencies" / "_index.md"

GOV_LABEL = {"executive_branch": "executive branch",
             "semi_independent": "semi-independent",
             "constitutional_elected": "constitutional elected",
             "unclassified": "unclassified"}


def build() -> str:
    rows = overview()
    L = ["# Agencies — overview",
         "",
         "Context about each agency's data, not just the data: governance class (cited",
         "in [`_meta/agency-profiles.yml`](../_meta/agency-profiles.yml)), where the",
         "agency publishes its policies, what this repo holds, and when its sources were",
         "last checked. GENERATED by `src/build_agency_index.py` — curate via the",
         "profiles file, never edit this page. Agency identity/hierarchy comes from the",
         "registry ([`_meta/catalog/agencies.yml`](../_meta/catalog/agencies.yml));",
         "look up any of the 172 registered agencies/sub-units (including the ~160 not",
         "yet ingested) via `python3 src/catalog_agencies.py \"<name>\"` or the MCP",
         "`agency_profile` tool.",
         "",
         "| Agency | Governance | Policies published | Docs | Verbatim | OCR-recovered | Unrecoverable | Last checked |",
         "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        # Only link agencies that have their own agencies/<slug>/ tree; sub-units'
        # docs often live in jurisdiction-wide dirs (rules/) or the parent's tree.
        name_cell = (f"[{r['name']}]({r['slug']}/_index.md)"
                     if (REPO_ROOT / "agencies" / r["slug"] / "_index.md").is_file()
                     else r["name"])
        L.append(f"| {name_cell} "
                 f"| {GOV_LABEL.get(r['governance'], r['governance'])} "
                 f"| {r['policies_published']} | {r['documents']} | {r['verbatim']} "
                 f"| {r['ocr_recovered']} | {r['content_exceptions']} "
                 f"| {r['last_checked'] or '—'} |")
    L.append("")
    L.append("Sub-units are listed under their own slug when they carry their own"
             " documents; a sub-unit's documents may also live under its parent's tree"
             " (see each agency's `_index.md`). 'Unrecoverable' = content_exception"
             " documents (image-only scans no OCR pass could pass the quality gate on).")
    L.append("")
    return "\n".join(L)


def main():
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("agencies/_index.md is stale — run: python3 src/build_agency_index.py")
            sys.exit(1)
        print("agencies/_index.md is current.")
        return
    OUT.write_text(text)
    print(f"agencies/_index.md regenerated: {text.count(chr(10))} lines")


if __name__ == "__main__":
    main()
