#!/usr/bin/env python3
"""Generate REVIEW.md — the single place listing everything that needs human
intervention or review. DERIVED, never hand-edited: every entry is computed from
ground truth already in the repo (frontmatter fields, body markers, catalog
statuses), so regenerating after any change keeps it complete and current.

  python3 src/review_queue.py           # regenerate REVIEW.md
  python3 src/review_queue.py --check   # exit 1 if committed REVIEW.md is stale (CI)
"""
import re
import sys
from pathlib import Path

import yaml

from repo_lib import REPO_ROOT, content_files, parse_frontmatter

OUT = REPO_ROOT / "REVIEW.md"
TODO_MARK = "TODO: human verification required"


def scan():
    q = {
        "exception": [],   # content_exception docs — zero machine verification
        "todo": [],        # explicit TODO markers in bodies/frontmatter
        "pending": [],     # status proposed/draft docs
        "migration": [],   # migration_pending
        "discrepancy": [], # curator-noted source/listing discrepancies
    }
    body_counts = {}
    for path in content_files():
        rel = str(path.relative_to(REPO_ROOT))
        fm, body = parse_frontmatter(path)
        top = rel.split("/")[0] if "/" not in rel.split("/", 2)[0] else rel
        body_key = "/".join(rel.split("/")[:-1])
        body_counts[body_key] = body_counts.get(body_key, 0) + 1
        if fm.get("content_exception"):
            q["exception"].append((rel, fm["content_exception"]))
        if fm.get("migration_pending"):
            q["migration"].append((rel, "legacy mixed-mode content awaiting full-text migration"))
        raw = path.read_text()
        if TODO_MARK in raw:
            for line in raw.splitlines():
                if TODO_MARK in line:
                    q["todo"].append((rel, line.strip()[:140]))
                    break
        if fm.get("status") in ("proposed", "draft"):
            q["pending"].append((rel, f"status: {fm['status']} — {fm.get('source_version', '')[:80]}"))
        if "Date discrepancy" in body:
            q["discrepancy"].append((rel, "document's printed date differs from the listing of record (see Curator notes)"))

    # catalog-derived items
    cat_items = {"not_sliceable": [], "renumbered": [], "gaps": []}
    ors = yaml.safe_load((REPO_ROOT / "_meta/catalog/ors.yml").read_text())
    for c in ors["chapters"]:
        for s in c["sections"]:
            if s.get("status") == "not_sliceable":
                cat_items["not_sliceable"].append((f"ORS {s['number']}", s.get("note", "")[:100]))
    oar = yaml.safe_load((REPO_ROOT / "_meta/catalog/oar.yml").read_text())
    for c in oar["chapters"]:
        for d in c["divisions"]:
            rules = d.get("rules")
            if isinstance(rules, list):
                for r in rules:
                    if r.get("status") in ("renumbered", "not_served", "not_sliceable"):
                        cat_items["renumbered"].append(
                            (f"OAR {r['number']}", f"{r['status']}: {r.get('note', '')[:90]}"))
                if not rules and d.get("status") == "not_ingested":
                    cat_items["gaps"].append(
                        (f"OAR chapter {c['chapter']} division {d['division']} ({d['title'][:50]})",
                         "no rules enumerated — not mirrored on oregon.public.law; needs another enumeration route"))
            elif d.get("status") == "not_ingested":
                cat_items["gaps"].append(
                    (f"OAR chapter {c['chapter']} division {d['division']} ({d['title'][:50]})",
                     "division never enumerated"))
    return q, cat_items, body_counts


def render(q, cat_items, body_counts):
    L = ["# Review queue — items needing human intervention",
         "",
         "**Generated by `src/review_queue.py` — do not edit by hand.** Every entry is",
         "derived from ground truth in the repo (frontmatter, body markers, catalogs);",
         "resolve an item at its source and regenerate. CI fails if this file is stale.",
         ""]

    def section(title, why, items, fmt=lambda a, b: f"- `{a}` — {b}"):
        L.append(f"## {title} ({len(items)})")
        L.append("")
        L.append(why)
        L.append("")
        for a, b in sorted(items):
            L.append(fmt(a, b))
        if not items:
            L.append("_(none)_")
        L.append("")

    section("Documents with NO machine verification — highest review priority",
            "These carry `content_exception`: their sources are image-only scans or binary "
            "forms, so nothing diffs them against a snapshot. A human must check each "
            "against its `source_url`. Resolve by OCR + full-text migration, or confirm "
            "the summary and record review in the file.",
            q["exception"])

    section("Explicit TODO markers",
            f"Files containing `{TODO_MARK}` — usually inserted by a source refresh: "
            "effective/version dates must be re-transcribed by a human from the changed "
            "source (HC-1 forbids assuming them). Resolve by editing the file and removing "
            "the marker.",
            q["todo"])

    section("Pending drafts — not current policy",
            "Documents whose own source (or the listing of record) marks them "
            "draft/proposed. No action needed until the upstream finalizes them "
            "(`/check-updates` will notice); review only if you need to know what's coming.",
            q["pending"])

    section("Source/listing discrepancies",
            "The document prints a different date than its listing of record (known site "
            "typos). This repo records what the document prints; each file's Curator notes "
            "explain. Review once; no fix needed unless upstream corrects itself.",
            q["discrepancy"])

    section("Catalog: sections with no sliceable body",
            "ORS catalog entries whose section text couldn't be found in the chapter HTML "
            "(likely renumbered/repealed or TOC noise). Verify against the printed ORS if "
            "any of these numbers matter; otherwise they stay intentionally not ingested.",
            cat_items["not_sliceable"])

    section("Catalog: renumbered / repealed rules (auto-resolved — verify mappings)",
            "OARD served a different rule number than requested; documents were filed "
            "under the served number and the mapping recorded. Spot-check that the "
            "mappings look right.",
            cat_items["renumbered"])

    section("Known enumeration gaps",
            "Corpus areas we know exist upstream but could not enumerate mechanically.",
            cat_items["gaps"])

    if q["migration"]:
        section("Legacy migration pending", "Mixed-mode content awaiting full-text migration.",
                q["migration"])

    L += ["## Standing item: human verification stamps",
          "",
          "`verified_by`/`last_verified` across the corpus record *machine* verification at",
          "ingestion time. No document has yet had a human read-through against its official",
          "source. When you review a file, update its `last_verified` to that date — that is",
          "the attestation the review gates call for. Corpus size by directory:",
          ""]
    for k in sorted(body_counts):
        L.append(f"- `{k}/`: {body_counts[k]} documents")
    L.append("")
    return "\n".join(L)


def main():
    q, cat_items, body_counts = scan()
    text = render(q, cat_items, body_counts)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("REVIEW.md is stale — run: python3 src/review_queue.py")
            sys.exit(1)
        print("REVIEW.md is current.")
        return
    OUT.write_text(text)
    total = sum(len(v) for v in q.values()) + sum(len(v) for v in cat_items.values())
    print(f"REVIEW.md regenerated: {total} item(s) across "
          f"{sum(1 for v in list(q.values()) + list(cat_items.values()) if v)} active section(s)")


if __name__ == "__main__":
    main()
